# Generated by Django 2.1.5 on 2019-03-08 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_account', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=63, verbose_name='Type user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrs', to=settings.AUTH_USER_MODEL, verbose_name='HR')),
            ],
            options={
                'verbose_name': 'Account hr',
                'verbose_name_plural': 'Account hrs',
            },
        ),
    ]
