version: '3'

services:

  nginx:
    container_name: phc_vr_nginx
    image: nginx:1.15.8-alpine
    depends_on:
      - backend
    volumes:
      - ../media:/media
      - ../static:/static
      - ./dev/conf.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "9163:80"

  postgresql:
    image: postgres:11.1-alpine
    container_name: phc_vr_postgres
    env_file: ./dev/.env_file
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: {context: ../, dockerfile: docker/dev/backend/Dockerfile}
    container_name: phc_vr_backend
    volumes:
      - ../media:/media
      - ../static:/static
    env_file:
      - ./dev/.env_file
    depends_on:
      - postgresql
    ports:
      - "5432:5432"
