# Generated by Django 2.1.5 on 2019-03-08 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0003_auto_20190227_1322'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_account', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=63, verbose_name='Type user')),
                ('resume', models.ManyToManyField(blank=True, related_name='resumes', to='resume.Resume', verbose_name='Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers_related', to=settings.AUTH_USER_MODEL, verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Account worker',
                'verbose_name_plural': 'Account workers',
            },
        ),
    ]
