# Generated by Django 2.1.5 on 2019-03-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('account_worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAnswered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_answers', to='question.Answer', verbose_name='Answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='question.Question', verbose_name='Questions')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_worker', to='account_worker.AccountWorker', verbose_name='Workers')),
            ],
        ),
    ]
