# Generated by Django 2.1.5 on 2019-03-15 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer'),
        ('account_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountworker',
            name='answer',
            field=models.ManyToManyField(related_name='answers', to='question.Answer', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='accountworker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='workers'),
        ),
    ]
