# Generated by Django 2.1.5 on 2019-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountworker',
            name='resume',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='resume.Resume', verbose_name='Resume'),
        ),
    ]
