# Generated by Django 2.1.7 on 2019-03-11 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountworker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='workers'),
        ),
    ]
