# Generated by Django 2.1.5 on 2019-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('account_hr', models.ManyToManyField(related_name='vacancies', to='account_hr.AccountHr', verbose_name='HRs')),
                ('tags', models.ManyToManyField(related_name='vacancies', to='vacancy.Tag', verbose_name='Tags')),
            ],
        ),
    ]
