# Generated by Django 2.1.5 on 2019-02-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20190220_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
