# Generated by Django 2.1.7 on 2019-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', max_length=256, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
