# Generated by Django 2.1.5 on 2019-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='account_hr',
            field=models.ManyToManyField(blank=True, related_name='questions', to='account_hr.AccountHr', verbose_name='HR'),
        ),
    ]
