# Generated by Django 2.1.5 on 2019-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.CharField(
                default='', max_length=400, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hobbies',
            field=models.CharField(
                default='', max_length=200, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='other_skills',
            field=models.CharField(
                default='', max_length=200, verbose_name='Other skills'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(
                default='', max_length=100, verbose_name='Title'),
        ),
    ]
