# Generated by Django 2.1.5 on 2019-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190226_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(
                allow_unicode=True, max_length=100, verbose_name='Slug'),
        ),
    ]
